server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: cyh2436986426
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: SH
#        namespace: 3d1d8a79-eea5-43d1-be24-d3e6be2517e3
#        ephemeral: false
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: userservice  #指定饥饿加载的服务
#userservice:
#  ribbon:
feign:
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #优先选择本地集群。在本地集群里，随机访问。如果同集群找不到，就跨集群访问，后端会报一个跨集群访问警告